# Generated by Django 6.0.5 on 2026-06-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="product_media/"),
        ),
    ]
