# Generated by Django 6.1 on 2026-09-22 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_item_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemHold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holds",
                        to="products.item",
                    ),
                ),
                (
                    "substitute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="substitute_holds",
                        to="products.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item hold",
                "verbose_name_plural": "Item holds",
            },
        ),
    ]
