[pytest]
DJANGO_SETTINGS_MODULE = examples.fakeshop.fakeshop.settings
pythonpath = examples/fakeshop
python_files = tests.py test_*.py *_tests.py
testpaths = tests examples/fakeshop/tests examples/fakeshop/test_query
addopts = -v --cov --cov-report=term-missing
