# Generated by Django 6.0.4 on 2026-05-27 00:00

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScalarSpecimen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.TextField(unique=True)),
                ("flag", models.BooleanField(default=False)),
                ("score", models.FloatField(default=0.0)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=20,
                    ),
                ),
                ("occurred_on", models.DateField()),
                ("occurred_at", models.DateTimeField()),
                ("occurred_time", models.TimeField()),
                ("payload", models.JSONField(default=dict)),
                ("external_id", models.UUIDField()),
                ("signed_big", models.BigIntegerField(default=0)),
                ("unsigned_big", models.PositiveBigIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="scalars.scalarspecimen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NullableScalarSpecimen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.TextField(blank=True, null=True, unique=True)),
                ("flag", models.BooleanField(blank=True, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                    ),
                ),
                ("occurred_on", models.DateField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("occurred_time", models.TimeField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("external_id", models.UUIDField(blank=True, null=True)),
                ("signed_big", models.BigIntegerField(blank=True, null=True)),
                ("unsigned_big", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nullable_partners",
                        to="scalars.scalarspecimen",
                    ),
                ),
            ],
        ),
    ]
