# Generated by Django 6.0.4 on 2026-05-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scalars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScalarSpecimenTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.TextField(unique=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="scalarspecimen",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tagged_specimens",
                to="scalars.scalarspecimentag",
            ),
        ),
    ]
