# Generated by Django 6.1 on 2026-09-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scalars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaspecimen",
            name="optional_attachment",
            field=models.FileField(blank=True, upload_to="scalar_media/files/"),
        ),
        migrations.AddField(
            model_name="mediaspecimen",
            name="spare_image",
            field=models.ImageField(null=True, upload_to="scalar_media/images/"),
        ),
    ]
