# Generated by Django 6.0.5 on 2026-06-08 21:13

from django.db import migrations, models

import apps.scalars.models


class Migration(migrations.Migration):
    dependencies = [
        ("scalars", "0002_scalar_specimen_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="OverrideSpecimen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.TextField()),
                ("quantity", models.IntegerField(default=0)),
                ("score", models.IntegerField(default=0)),
                ("token", apps.scalars.models.Base36Field()),
            ],
        ),
    ]
