# Generated by Django 6.0.5 on 2026-06-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scalars", "0003_overridespecimen"),
    ]

    operations = [
        migrations.AddField(
            model_name="overridespecimen",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
