# Generated by Django 6.0.5 on 2026-06-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scalars", "0004_overridespecimen_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaSpecimen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.TextField(unique=True)),
                ("attachment", models.FileField(upload_to="scalar_media/files/")),
                ("image", models.ImageField(upload_to="scalar_media/images/")),
            ],
        ),
    ]
