"""The PG EXPLAIN artifact carries a regenerable, valid link-definition footer.

The Part 1 EXPLAIN artifact (``docs/row-preserving-predicates-part1-pg-explain.md``)
is a standing "do not hand-edit" doc generated by
``scripts/capture_pg_predicate_explain.py``. Standing docs must end with the
canonical ``<!-- LINK DEFINITIONS -->`` footer (AGENTS.md "Markdown link
convention"), so the generator must EMIT that footer itself -- otherwise running
the documented regeneration command would strip the hand-added footer and leave
an artifact that cannot be regenerated without violating the standing-doc rule.

These are pure package unit tests (no Postgres, no Django setup, no db): the
capture module defers every django/db import into its functions, so importing it
for the footer constant is safe under the default (non-``pg``) ``pytest`` run.
"""

from scripts.capture_pg_predicate_explain import (
    ARTIFACT_PATH,
    LINK_DEFINITIONS_FOOTER,
)
from scripts.check_trailing_commas import (
    LINK_DEF_CATEGORIES,
    LINK_DEF_HEADER,
    _scaffold_in_canonical_order,
)


def test_footer_constant_has_all_canonical_headers_in_order():
    """The generator's footer constant is a single, correctly ordered scaffold."""
    # Exactly one delimiter -- the whole footer sits under one LINK-DEFINITIONS block.
    assert LINK_DEFINITIONS_FOOTER.count(LINK_DEF_HEADER) == 1
    # Every canonical group header appears, each strictly after the previous one.
    pos = LINK_DEFINITIONS_FOOTER.find(LINK_DEF_HEADER)
    assert pos >= 0
    pos += len(LINK_DEF_HEADER)
    for header in LINK_DEF_CATEGORIES:
        nxt = LINK_DEFINITIONS_FOOTER.find(header, pos)
        assert nxt >= pos, f"{header!r} missing or out of order"
        pos = nxt + len(header)
    # The scaffold validator that gates every standing doc accepts the constant.
    # It names the first missing/out-of-order marker, so ``None`` is the pass.
    assert _scaffold_in_canonical_order(LINK_DEFINITIONS_FOOTER) is None


def test_checked_in_artifact_passes_link_block_validation():
    """The checked-in artifact validates and its tail matches the emitted footer."""
    text = ARTIFACT_PATH.read_text(encoding="utf-8")
    # Same standing-doc link-block validation ``check_trailing_commas`` runs.
    assert _scaffold_in_canonical_order(text) is None
    # The generator composes ``"\n".join(lines) + "\n" + LINK_DEFINITIONS_FOOTER``;
    # ``"\n".join(lines)`` ends in a newline, so a regenerated file ends in exactly
    # this tail. Asserting it proves the footer emission is byte-identical to the
    # checked-in artifact (the generator can regenerate without stripping it).
    assert text.endswith("\n\n" + LINK_DEFINITIONS_FOOTER)
