# Generated by Django 6.0.5 on 2026-06-23 03:47

import uuid

import django.db.models.deletion
import django.db.models.lookups
from django.db import migrations, models

import apps.kanban.constraints


def copy_target_version_milestones(apps, schema_editor):
    Card = apps.get_model("kanban", "Card")
    db_alias = schema_editor.connection.alias
    for card in (
        Card.objects.using(db_alias)
        .filter(milestone__isnull=True)
        .select_related("target_version")
    ):
        card.milestone_id = card.target_version.milestone_id
        card.save(update_fields=["milestone"])


def move_spec_links_to_spec_docs(apps, schema_editor):
    Card = apps.get_model("kanban", "Card")
    SpecDoc = apps.get_model("kanban", "SpecDoc")
    db_alias = schema_editor.connection.alias

    for card in Card.objects.using(db_alias).filter(spec__isnull=False):
        SpecDoc.objects.using(db_alias).filter(pk=card.spec_id).update(card_id=card.pk)

    orphan_names = list(
        SpecDoc.objects.using(db_alias).filter(card__isnull=True).values_list("name", flat=True),
    )
    if orphan_names:
        raise ValueError(
            "Cannot require SpecDoc.card while orphan spec docs exist: " + ", ".join(orphan_names),
        )


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("color", models.TextField(blank=True, default="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("label", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("version_floor", models.TextField(blank=True, default="")),
                ("version_ceiling", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ParityLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("label", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlanningState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("label", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Priority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("label", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "priorities",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RelativeSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("label", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("rank", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("label", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Severity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("label", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "severities",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpecDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("url", models.URLField(max_length=500)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("label", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "statuses",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Upstream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("label", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("emoji", models.TextField(blank=True, default="")),
                ("homepage", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("title", models.TextField(unique=True)),
                ("number", models.PositiveIntegerField()),
                ("planning_note", models.TextField(blank=True, default="")),
                ("summary", models.TextField(blank=True, default="")),
                ("body", models.TextField(blank=True, default="")),
                (
                    "dependencies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dependents",
                        to="kanban.card",
                    ),
                ),
                (
                    "labels",
                    models.ManyToManyField(blank=True, related_name="cards", to="kanban.label"),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cards",
                        to="kanban.milestone",
                    ),
                ),
                (
                    "planning_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cards",
                        to="kanban.planningstate",
                    ),
                ),
                (
                    "priority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cards",
                        to="kanban.priority",
                    ),
                ),
                (
                    "relative_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cards",
                        to="kanban.relativesize",
                    ),
                ),
                (
                    "relative_size_high",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cards_high",
                        to="kanban.relativesize",
                    ),
                ),
                (
                    "severity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cards",
                        to="kanban.severity",
                    ),
                ),
                (
                    "spec",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card",
                        to="kanban.specdoc",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cards",
                        to="kanban.status",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="CardItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="kanban.card",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="kanban.section",
                    ),
                ),
            ],
            options={
                "ordering": ["card", "section", "order"],
            },
        ),
        migrations.CreateModel(
            name="TargetVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("number", models.TextField(unique=True)),
                ("shipped_on", models.DateField(blank=True, null=True)),
                ("git_ref", models.TextField(blank=True, default="")),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="target_versions",
                        to="kanban.milestone",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.AddField(
            model_name="card",
            name="target_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cards",
                to="kanban.targetversion",
            ),
        ),
        migrations.CreateModel(
            name="ParityClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parity_claims",
                        to="kanban.card",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parity_claims",
                        to="kanban.paritylevel",
                    ),
                ),
                (
                    "upstream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parity_claims",
                        to="kanban.upstream",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="card",
            name="parity",
            field=models.ManyToManyField(
                blank=True,
                related_name="cards",
                through="kanban.ParityClaim",
                to="kanban.upstream",
            ),
        ),
        migrations.CreateModel(
            name="UUIDModel",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "card",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uuid",
                        to="kanban.card",
                    ),
                ),
                (
                    "carditem",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uuid",
                        to="kanban.carditem",
                    ),
                ),
                (
                    "label",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uuid",
                        to="kanban.label",
                    ),
                ),
                (
                    "milestone",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uuid",
                        to="kanban.milestone",
                    ),
                ),
                (
                    "parityclaim",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uuid",
                        to="kanban.parityclaim",
                    ),
                ),
                (
                    "paritylevel",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uuid",
                        to="kanban.paritylevel",
                    ),
                ),
                (
                    "planningstate",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uuid",
                        to="kanban.planningstate",
                    ),
                ),
                (
                    "priority",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uuid",
                        to="kanban.priority",
                    ),
                ),
                (
                    "relativesize",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uuid",
                        to="kanban.relativesize",
                    ),
                ),
                (
                    "section",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uuid",
                        to="kanban.section",
                    ),
                ),
                (
                    "severity",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uuid",
                        to="kanban.severity",
                    ),
                ),
                (
                    "specdoc",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uuid",
                        to="kanban.specdoc",
                    ),
                ),
                (
                    "status",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uuid",
                        to="kanban.status",
                    ),
                ),
                (
                    "targetversion",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uuid",
                        to="kanban.targetversion",
                    ),
                ),
                (
                    "upstream",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uuid",
                        to="kanban.upstream",
                    ),
                ),
            ],
            options={
                "verbose_name": "UUID",
                "verbose_name_plural": "UUIDs",
            },
        ),
        migrations.AddConstraint(
            model_name="parityclaim",
            constraint=models.UniqueConstraint(
                fields=("card", "upstream"),
                name="unique_parity_per_card_upstream",
            ),
        ),
        migrations.AddConstraint(
            model_name="uuidmodel",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    apps.kanban.constraints.OneHotLinkCount(
                        "milestone",
                        "status",
                        "priority",
                        "severity",
                        "relativesize",
                        "planningstate",
                        "upstream",
                        "paritylevel",
                        "section",
                        "targetversion",
                        "specdoc",
                        "card",
                        "parityclaim",
                        "carditem",
                        "label",
                    ),
                    models.Value(1),
                ),
                name="kanban_uuidmodel_exactly_one_link",
            ),
        ),
        migrations.AlterModelOptions(
            name="card",
            options={
                "ordering": ["number"],
                "verbose_name": "card",
                "verbose_name_plural": "cards",
            },
        ),
        migrations.AlterModelOptions(
            name="carditem",
            options={
                "ordering": ["card", "section", "order"],
                "verbose_name": "card item",
                "verbose_name_plural": "card items",
            },
        ),
        migrations.AlterModelOptions(
            name="label",
            options={"verbose_name": "label", "verbose_name_plural": "labels"},
        ),
        migrations.AlterModelOptions(
            name="milestone",
            options={
                "ordering": ["order"],
                "verbose_name": "milestone",
                "verbose_name_plural": "milestones",
            },
        ),
        migrations.AlterModelOptions(
            name="parityclaim",
            options={"verbose_name": "parity claim", "verbose_name_plural": "parity claims"},
        ),
        migrations.AlterModelOptions(
            name="paritylevel",
            options={
                "ordering": ["order"],
                "verbose_name": "parity level",
                "verbose_name_plural": "parity levels",
            },
        ),
        migrations.AlterModelOptions(
            name="planningstate",
            options={
                "ordering": ["order"],
                "verbose_name": "planning state",
                "verbose_name_plural": "planning states",
            },
        ),
        migrations.AlterModelOptions(
            name="priority",
            options={
                "ordering": ["order"],
                "verbose_name": "priority",
                "verbose_name_plural": "priorities",
            },
        ),
        migrations.AlterModelOptions(
            name="relativesize",
            options={
                "ordering": ["order"],
                "verbose_name": "relative size",
                "verbose_name_plural": "relative sizes",
            },
        ),
        migrations.AlterModelOptions(
            name="section",
            options={
                "ordering": ["order"],
                "verbose_name": "section",
                "verbose_name_plural": "sections",
            },
        ),
        migrations.AlterModelOptions(
            name="severity",
            options={
                "ordering": ["order"],
                "verbose_name": "severity",
                "verbose_name_plural": "severities",
            },
        ),
        migrations.AlterModelOptions(
            name="specdoc",
            options={"verbose_name": "spec doc", "verbose_name_plural": "spec docs"},
        ),
        migrations.AlterModelOptions(
            name="status",
            options={
                "ordering": ["order"],
                "verbose_name": "status",
                "verbose_name_plural": "statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="targetversion",
            options={
                "ordering": ["number"],
                "verbose_name": "target version",
                "verbose_name_plural": "target versions",
            },
        ),
        migrations.AlterModelOptions(
            name="upstream",
            options={
                "ordering": ["order"],
                "verbose_name": "upstream",
                "verbose_name_plural": "upstreams",
            },
        ),
        migrations.AlterField(
            model_name="specdoc",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(fields=["number"], name="kanban_card_number_aa2857_idx"),
        ),
        migrations.AddConstraint(
            model_name="card",
            constraint=models.UniqueConstraint(
                fields=("status", "number", "target_version"),
                name="unique_card_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="carditem",
            constraint=models.UniqueConstraint(
                fields=("card", "section", "order"),
                name="unique_item_position_per_card",
            ),
        ),
        migrations.CreateModel(
            name="CardReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("raw_text", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "card reference",
                "verbose_name_plural": "card references",
                "ordering": ["source_card", "source", "order"],
            },
        ),
        migrations.CreateModel(
            name="CardReferenceKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("label", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "card reference kind",
                "verbose_name_plural": "card reference kinds",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CardReferenceSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("label", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "card reference source",
                "verbose_name_plural": "card reference sources",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="uuidmodel",
            name="kanban_uuidmodel_exactly_one_link",
        ),
        migrations.AddField(
            model_name="cardreference",
            name="source_card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_references",
                to="kanban.card",
            ),
        ),
        migrations.AddField(
            model_name="cardreference",
            name="target_card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_references",
                to="kanban.card",
            ),
        ),
        migrations.AddField(
            model_name="uuidmodel",
            name="cardreference",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uuid",
                to="kanban.cardreference",
            ),
        ),
        migrations.AddField(
            model_name="cardreference",
            name="kind",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="card_references",
                to="kanban.cardreferencekind",
            ),
        ),
        migrations.AddField(
            model_name="uuidmodel",
            name="cardreferencekind",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uuid",
                to="kanban.cardreferencekind",
            ),
        ),
        migrations.AddField(
            model_name="cardreference",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="card_references",
                to="kanban.cardreferencesource",
            ),
        ),
        migrations.AddField(
            model_name="uuidmodel",
            name="cardreferencesource",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uuid",
                to="kanban.cardreferencesource",
            ),
        ),
        migrations.AddConstraint(
            model_name="uuidmodel",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    apps.kanban.constraints.OneHotLinkCount(
                        "milestone",
                        "status",
                        "priority",
                        "severity",
                        "relativesize",
                        "planningstate",
                        "upstream",
                        "paritylevel",
                        "section",
                        "cardreferencekind",
                        "cardreferencesource",
                        "targetversion",
                        "specdoc",
                        "card",
                        "cardreference",
                        "parityclaim",
                        "carditem",
                        "label",
                    ),
                    models.Value(1),
                ),
                name="kanban_uuidmodel_exactly_one_link",
            ),
        ),
        migrations.AddIndex(
            model_name="cardreference",
            index=models.Index(
                fields=["target_card", "kind"],
                name="kanban_card_target__3157a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cardreference",
            index=models.Index(
                fields=["source_card", "kind"],
                name="kanban_card_source__7f7dd8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="cardreference",
            constraint=models.UniqueConstraint(
                fields=("source_card", "source", "order"),
                name="unique_card_reference_position",
            ),
        ),
        migrations.RemoveField(
            model_name="card",
            name="body",
        ),
        migrations.RemoveField(
            model_name="card",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="description",
        ),
        migrations.RemoveField(
            model_name="parityclaim",
            name="note",
        ),
        migrations.RemoveField(
            model_name="targetversion",
            name="git_ref",
        ),
        migrations.RemoveField(
            model_name="targetversion",
            name="shipped_on",
        ),
        migrations.RemoveField(
            model_name="upstream",
            name="homepage",
        ),
        migrations.CreateModel(
            name="BoardDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("title", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
                ("body", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "board doc",
                "verbose_name_plural": "board docs",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="BoardDocKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("label", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "board doc kind",
                "verbose_name_plural": "board doc kinds",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="uuidmodel",
            name="kanban_uuidmodel_exactly_one_link",
        ),
        migrations.AddField(
            model_name="uuidmodel",
            name="boarddoc",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uuid",
                to="kanban.boarddoc",
            ),
        ),
        migrations.AddField(
            model_name="boarddoc",
            name="kind",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="docs",
                to="kanban.boarddockind",
            ),
        ),
        migrations.AddField(
            model_name="uuidmodel",
            name="boarddockind",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uuid",
                to="kanban.boarddockind",
            ),
        ),
        migrations.AddConstraint(
            model_name="uuidmodel",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    apps.kanban.constraints.OneHotLinkCount(
                        "milestone",
                        "status",
                        "priority",
                        "severity",
                        "relativesize",
                        "planningstate",
                        "upstream",
                        "paritylevel",
                        "section",
                        "cardreferencekind",
                        "cardreferencesource",
                        "boarddockind",
                        "targetversion",
                        "specdoc",
                        "card",
                        "cardreference",
                        "parityclaim",
                        "carditem",
                        "label",
                        "boarddoc",
                    ),
                    models.Value(1),
                ),
                name="kanban_uuidmodel_exactly_one_link",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="card",
            name="unique_card_id",
        ),
        migrations.RemoveIndex(
            model_name="card",
            name="kanban_card_number_aa2857_idx",
        ),
        migrations.AlterField(
            model_name="card",
            name="number",
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.CreateModel(
            name="BoardDocCardReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("raw_text", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "board doc card reference",
                "verbose_name_plural": "board doc card references",
                "ordering": ["doc", "order"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="uuidmodel",
            name="kanban_uuidmodel_exactly_one_link",
        ),
        migrations.AddField(
            model_name="boarddoccardreference",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="board_doc_references",
                to="kanban.card",
            ),
        ),
        migrations.AddField(
            model_name="boarddoccardreference",
            name="doc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_references",
                to="kanban.boarddoc",
            ),
        ),
        migrations.AddField(
            model_name="uuidmodel",
            name="boarddoccardreference",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uuid",
                to="kanban.boarddoccardreference",
            ),
        ),
        migrations.AddConstraint(
            model_name="uuidmodel",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    apps.kanban.constraints.OneHotLinkCount(
                        "milestone",
                        "status",
                        "priority",
                        "severity",
                        "relativesize",
                        "planningstate",
                        "upstream",
                        "paritylevel",
                        "section",
                        "cardreferencekind",
                        "cardreferencesource",
                        "boarddockind",
                        "targetversion",
                        "specdoc",
                        "card",
                        "cardreference",
                        "parityclaim",
                        "carditem",
                        "label",
                        "boarddoc",
                        "boarddoccardreference",
                    ),
                    models.Value(1),
                ),
                name="kanban_uuidmodel_exactly_one_link",
            ),
        ),
        migrations.AddIndex(
            model_name="boarddoccardreference",
            index=models.Index(fields=["card"], name="kanban_boar_card_id_459870_idx"),
        ),
        migrations.AddConstraint(
            model_name="boarddoccardreference",
            constraint=models.UniqueConstraint(
                fields=("doc", "order"),
                name="unique_board_doc_card_reference_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="targetversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("number", ""), _negated=True),
                name="target_version_number_required",
            ),
        ),
        migrations.RunPython(
            code=copy_target_version_milestones,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="card",
            name="milestone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cards",
                to="kanban.milestone",
            ),
        ),
        migrations.AddConstraint(
            model_name="card",
            constraint=models.CheckConstraint(
                condition=models.Q(("number__gte", 1)),
                name="card_number_required",
            ),
        ),
        migrations.AddField(
            model_name="specdoc",
            name="card",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spec_docs_during_migration",
                to="kanban.card",
            ),
        ),
        migrations.RunPython(
            code=move_spec_links_to_spec_docs,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="card",
            name="spec",
        ),
        migrations.AlterField(
            model_name="specdoc",
            name="card",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spec",
                to="kanban.card",
            ),
        ),
        migrations.AlterModelOptions(
            name="boarddoc",
            options={
                "ordering": ["namespace", "order"],
                "verbose_name": "board doc",
                "verbose_name_plural": "board docs",
            },
        ),
        migrations.AddField(
            model_name="boarddoc",
            name="include_heading",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="boarddoc",
            name="namespace",
            field=models.SlugField(default="kanban"),
        ),
        migrations.AlterField(
            model_name="boarddoc",
            name="key",
            field=models.SlugField(),
        ),
        migrations.AddConstraint(
            model_name="boarddoc",
            constraint=models.UniqueConstraint(
                fields=("namespace", "key"),
                name="unique_board_doc_key_per_namespace",
            ),
        ),
    ]
