# Generated by Django 6.0.5 on 2026-05-29 04:25

import django.db.models.expressions
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="uuidmodel",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    django.db.models.expressions.CombinedExpression(
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        django.db.models.expressions.CombinedExpression(
                                            django.db.models.expressions.CombinedExpression(
                                                django.db.models.expressions.CombinedExpression(
                                                    django.db.models.expressions.CombinedExpression(
                                                        django.db.models.expressions.CombinedExpression(
                                                            django.db.models.expressions.CombinedExpression(
                                                                django.db.models.expressions.CombinedExpression(
                                                                    django.db.models.expressions.CombinedExpression(
                                                                        django.db.models.expressions.CombinedExpression(
                                                                            models.Case(
                                                                                models.When(
                                                                                    milestone__isnull=False,
                                                                                    then=1,
                                                                                ),
                                                                                default=0,
                                                                                output_field=models.IntegerField(),
                                                                            ),
                                                                            "+",
                                                                            models.Case(
                                                                                models.When(
                                                                                    status__isnull=False,
                                                                                    then=1,
                                                                                ),
                                                                                default=0,
                                                                                output_field=models.IntegerField(),
                                                                            ),
                                                                        ),
                                                                        "+",
                                                                        models.Case(
                                                                            models.When(
                                                                                priority__isnull=False,
                                                                                then=1,
                                                                            ),
                                                                            default=0,
                                                                            output_field=models.IntegerField(),
                                                                        ),
                                                                    ),
                                                                    "+",
                                                                    models.Case(
                                                                        models.When(
                                                                            severity__isnull=False,
                                                                            then=1,
                                                                        ),
                                                                        default=0,
                                                                        output_field=models.IntegerField(),
                                                                    ),
                                                                ),
                                                                "+",
                                                                models.Case(
                                                                    models.When(
                                                                        relativesize__isnull=False,
                                                                        then=1,
                                                                    ),
                                                                    default=0,
                                                                    output_field=models.IntegerField(),
                                                                ),
                                                            ),
                                                            "+",
                                                            models.Case(
                                                                models.When(
                                                                    planningstate__isnull=False,
                                                                    then=1,
                                                                ),
                                                                default=0,
                                                                output_field=models.IntegerField(),
                                                            ),
                                                        ),
                                                        "+",
                                                        models.Case(
                                                            models.When(
                                                                then=1,
                                                                upstream__isnull=False,
                                                            ),
                                                            default=0,
                                                            output_field=models.IntegerField(),
                                                        ),
                                                    ),
                                                    "+",
                                                    models.Case(
                                                        models.When(
                                                            paritylevel__isnull=False,
                                                            then=1,
                                                        ),
                                                        default=0,
                                                        output_field=models.IntegerField(),
                                                    ),
                                                ),
                                                "+",
                                                models.Case(
                                                    models.When(section__isnull=False, then=1),
                                                    default=0,
                                                    output_field=models.IntegerField(),
                                                ),
                                            ),
                                            "+",
                                            models.Case(
                                                models.When(targetversion__isnull=False, then=1),
                                                default=0,
                                                output_field=models.IntegerField(),
                                            ),
                                        ),
                                        "+",
                                        models.Case(
                                            models.When(specdoc__isnull=False, then=1),
                                            default=0,
                                            output_field=models.IntegerField(),
                                        ),
                                    ),
                                    "+",
                                    models.Case(
                                        models.When(card__isnull=False, then=1),
                                        default=0,
                                        output_field=models.IntegerField(),
                                    ),
                                ),
                                "+",
                                models.Case(
                                    models.When(parityclaim__isnull=False, then=1),
                                    default=0,
                                    output_field=models.IntegerField(),
                                ),
                            ),
                            "+",
                            models.Case(
                                models.When(carditem__isnull=False, then=1),
                                default=0,
                                output_field=models.IntegerField(),
                            ),
                        ),
                        "+",
                        models.Case(
                            models.When(label__isnull=False, then=1),
                            default=0,
                            output_field=models.IntegerField(),
                        ),
                    ),
                    models.Value(1),
                ),
                name="kanban_uuidmodel_exactly_one_link",
            ),
        ),
    ]
