# Generated by Django 6.0.5 on 2026-05-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0002_uuidmodel_kanban_uuidmodel_exactly_one_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={
                "ordering": ["number"],
                "verbose_name": "card",
                "verbose_name_plural": "cards",
            },
        ),
        migrations.AlterModelOptions(
            name="carditem",
            options={
                "ordering": ["card", "section", "order"],
                "verbose_name": "card item",
                "verbose_name_plural": "card items",
            },
        ),
        migrations.AlterModelOptions(
            name="label",
            options={"verbose_name": "label", "verbose_name_plural": "labels"},
        ),
        migrations.AlterModelOptions(
            name="milestone",
            options={
                "ordering": ["order"],
                "verbose_name": "milestone",
                "verbose_name_plural": "milestones",
            },
        ),
        migrations.AlterModelOptions(
            name="parityclaim",
            options={"verbose_name": "parity claim", "verbose_name_plural": "parity claims"},
        ),
        migrations.AlterModelOptions(
            name="paritylevel",
            options={
                "ordering": ["order"],
                "verbose_name": "parity level",
                "verbose_name_plural": "parity levels",
            },
        ),
        migrations.AlterModelOptions(
            name="planningstate",
            options={
                "ordering": ["order"],
                "verbose_name": "planning state",
                "verbose_name_plural": "planning states",
            },
        ),
        migrations.AlterModelOptions(
            name="priority",
            options={
                "ordering": ["order"],
                "verbose_name": "priority",
                "verbose_name_plural": "priorities",
            },
        ),
        migrations.AlterModelOptions(
            name="relativesize",
            options={
                "ordering": ["order"],
                "verbose_name": "relative size",
                "verbose_name_plural": "relative sizes",
            },
        ),
        migrations.AlterModelOptions(
            name="section",
            options={
                "ordering": ["order"],
                "verbose_name": "section",
                "verbose_name_plural": "sections",
            },
        ),
        migrations.AlterModelOptions(
            name="severity",
            options={
                "ordering": ["order"],
                "verbose_name": "severity",
                "verbose_name_plural": "severities",
            },
        ),
        migrations.AlterModelOptions(
            name="specdoc",
            options={"verbose_name": "spec doc", "verbose_name_plural": "spec docs"},
        ),
        migrations.AlterModelOptions(
            name="status",
            options={
                "ordering": ["order"],
                "verbose_name": "status",
                "verbose_name_plural": "statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="targetversion",
            options={
                "ordering": ["number"],
                "verbose_name": "target version",
                "verbose_name_plural": "target versions",
            },
        ),
        migrations.AlterModelOptions(
            name="upstream",
            options={
                "ordering": ["order"],
                "verbose_name": "upstream",
                "verbose_name_plural": "upstreams",
            },
        ),
        migrations.AlterField(
            model_name="specdoc",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(fields=["number"], name="kanban_card_number_aa2857_idx"),
        ),
        migrations.AddConstraint(
            model_name="card",
            constraint=models.UniqueConstraint(
                fields=("status", "number", "target_version"),
                name="unique_card_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="carditem",
            constraint=models.UniqueConstraint(
                fields=("card", "section", "order"),
                name="unique_item_position_per_card",
            ),
        ),
    ]
