# Generated by Django 6.0.5 on 2026-05-30 16:25

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0003_alter_card_options_alter_carditem_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("raw_text", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "card reference",
                "verbose_name_plural": "card references",
                "ordering": ["source_card", "source", "order"],
            },
        ),
        migrations.CreateModel(
            name="CardReferenceKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("label", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "card reference kind",
                "verbose_name_plural": "card reference kinds",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CardReferenceSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("label", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "card reference source",
                "verbose_name_plural": "card reference sources",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="uuidmodel",
            name="kanban_uuidmodel_exactly_one_link",
        ),
        migrations.AddField(
            model_name="cardreference",
            name="source_card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_references",
                to="kanban.card",
            ),
        ),
        migrations.AddField(
            model_name="cardreference",
            name="target_card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_references",
                to="kanban.card",
            ),
        ),
        migrations.AddField(
            model_name="uuidmodel",
            name="cardreference",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uuid",
                to="kanban.cardreference",
            ),
        ),
        migrations.AddField(
            model_name="cardreference",
            name="kind",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="card_references",
                to="kanban.cardreferencekind",
            ),
        ),
        migrations.AddField(
            model_name="uuidmodel",
            name="cardreferencekind",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uuid",
                to="kanban.cardreferencekind",
            ),
        ),
        migrations.AddField(
            model_name="cardreference",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="card_references",
                to="kanban.cardreferencesource",
            ),
        ),
        migrations.AddField(
            model_name="uuidmodel",
            name="cardreferencesource",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uuid",
                to="kanban.cardreferencesource",
            ),
        ),
        migrations.AddConstraint(
            model_name="uuidmodel",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    django.db.models.expressions.CombinedExpression(
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        django.db.models.expressions.CombinedExpression(
                                            django.db.models.expressions.CombinedExpression(
                                                django.db.models.expressions.CombinedExpression(
                                                    django.db.models.expressions.CombinedExpression(
                                                        django.db.models.expressions.CombinedExpression(
                                                            django.db.models.expressions.CombinedExpression(
                                                                django.db.models.expressions.CombinedExpression(
                                                                    django.db.models.expressions.CombinedExpression(
                                                                        django.db.models.expressions.CombinedExpression(
                                                                            django.db.models.expressions.CombinedExpression(
                                                                                django.db.models.expressions.CombinedExpression(
                                                                                    django.db.models.expressions.CombinedExpression(
                                                                                        models.Case(
                                                                                            models.When(
                                                                                                milestone__isnull=False,
                                                                                                then=1,
                                                                                            ),
                                                                                            default=0,
                                                                                            output_field=models.IntegerField(),
                                                                                        ),
                                                                                        "+",
                                                                                        models.Case(
                                                                                            models.When(
                                                                                                status__isnull=False,
                                                                                                then=1,
                                                                                            ),
                                                                                            default=0,
                                                                                            output_field=models.IntegerField(),
                                                                                        ),
                                                                                    ),
                                                                                    "+",
                                                                                    models.Case(
                                                                                        models.When(
                                                                                            priority__isnull=False,
                                                                                            then=1,
                                                                                        ),
                                                                                        default=0,
                                                                                        output_field=models.IntegerField(),
                                                                                    ),
                                                                                ),
                                                                                "+",
                                                                                models.Case(
                                                                                    models.When(
                                                                                        severity__isnull=False,
                                                                                        then=1,
                                                                                    ),
                                                                                    default=0,
                                                                                    output_field=models.IntegerField(),
                                                                                ),
                                                                            ),
                                                                            "+",
                                                                            models.Case(
                                                                                models.When(
                                                                                    relativesize__isnull=False,
                                                                                    then=1,
                                                                                ),
                                                                                default=0,
                                                                                output_field=models.IntegerField(),
                                                                            ),
                                                                        ),
                                                                        "+",
                                                                        models.Case(
                                                                            models.When(
                                                                                planningstate__isnull=False,
                                                                                then=1,
                                                                            ),
                                                                            default=0,
                                                                            output_field=models.IntegerField(),
                                                                        ),
                                                                    ),
                                                                    "+",
                                                                    models.Case(
                                                                        models.When(
                                                                            then=1,
                                                                            upstream__isnull=False,
                                                                        ),
                                                                        default=0,
                                                                        output_field=models.IntegerField(),
                                                                    ),
                                                                ),
                                                                "+",
                                                                models.Case(
                                                                    models.When(
                                                                        paritylevel__isnull=False,
                                                                        then=1,
                                                                    ),
                                                                    default=0,
                                                                    output_field=models.IntegerField(),
                                                                ),
                                                            ),
                                                            "+",
                                                            models.Case(
                                                                models.When(
                                                                    section__isnull=False,
                                                                    then=1,
                                                                ),
                                                                default=0,
                                                                output_field=models.IntegerField(),
                                                            ),
                                                        ),
                                                        "+",
                                                        models.Case(
                                                            models.When(
                                                                cardreferencekind__isnull=False,
                                                                then=1,
                                                            ),
                                                            default=0,
                                                            output_field=models.IntegerField(),
                                                        ),
                                                    ),
                                                    "+",
                                                    models.Case(
                                                        models.When(
                                                            cardreferencesource__isnull=False,
                                                            then=1,
                                                        ),
                                                        default=0,
                                                        output_field=models.IntegerField(),
                                                    ),
                                                ),
                                                "+",
                                                models.Case(
                                                    models.When(
                                                        targetversion__isnull=False,
                                                        then=1,
                                                    ),
                                                    default=0,
                                                    output_field=models.IntegerField(),
                                                ),
                                            ),
                                            "+",
                                            models.Case(
                                                models.When(specdoc__isnull=False, then=1),
                                                default=0,
                                                output_field=models.IntegerField(),
                                            ),
                                        ),
                                        "+",
                                        models.Case(
                                            models.When(card__isnull=False, then=1),
                                            default=0,
                                            output_field=models.IntegerField(),
                                        ),
                                    ),
                                    "+",
                                    models.Case(
                                        models.When(cardreference__isnull=False, then=1),
                                        default=0,
                                        output_field=models.IntegerField(),
                                    ),
                                ),
                                "+",
                                models.Case(
                                    models.When(parityclaim__isnull=False, then=1),
                                    default=0,
                                    output_field=models.IntegerField(),
                                ),
                            ),
                            "+",
                            models.Case(
                                models.When(carditem__isnull=False, then=1),
                                default=0,
                                output_field=models.IntegerField(),
                            ),
                        ),
                        "+",
                        models.Case(
                            models.When(label__isnull=False, then=1),
                            default=0,
                            output_field=models.IntegerField(),
                        ),
                    ),
                    models.Value(1),
                ),
                name="kanban_uuidmodel_exactly_one_link",
            ),
        ),
        migrations.AddIndex(
            model_name="cardreference",
            index=models.Index(
                fields=["target_card", "kind"],
                name="kanban_card_target__3157a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cardreference",
            index=models.Index(
                fields=["source_card", "kind"],
                name="kanban_card_source__7f7dd8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="cardreference",
            constraint=models.UniqueConstraint(
                fields=("source_card", "source", "order"),
                name="unique_card_reference_position",
            ),
        ),
    ]
