# Generated by Django 6.0.5 on 2026-05-30 21:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0004_card_reference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="body",
        ),
        migrations.RemoveField(
            model_name="card",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="description",
        ),
        migrations.RemoveField(
            model_name="parityclaim",
            name="note",
        ),
        migrations.RemoveField(
            model_name="targetversion",
            name="git_ref",
        ),
        migrations.RemoveField(
            model_name="targetversion",
            name="shipped_on",
        ),
        migrations.RemoveField(
            model_name="upstream",
            name="homepage",
        ),
    ]
