# Generated by Django 6.0.5 on 2026-05-30 21:48

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0005_remove_card_body_remove_card_summary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("title", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
                ("body", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "board doc",
                "verbose_name_plural": "board docs",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="BoardDocKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("label", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "board doc kind",
                "verbose_name_plural": "board doc kinds",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="uuidmodel",
            name="kanban_uuidmodel_exactly_one_link",
        ),
        migrations.AddField(
            model_name="uuidmodel",
            name="boarddoc",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uuid",
                to="kanban.boarddoc",
            ),
        ),
        migrations.AddField(
            model_name="boarddoc",
            name="kind",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="docs",
                to="kanban.boarddockind",
            ),
        ),
        migrations.AddField(
            model_name="uuidmodel",
            name="boarddockind",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uuid",
                to="kanban.boarddockind",
            ),
        ),
        migrations.AddConstraint(
            model_name="uuidmodel",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    django.db.models.expressions.CombinedExpression(
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        django.db.models.expressions.CombinedExpression(
                                            django.db.models.expressions.CombinedExpression(
                                                django.db.models.expressions.CombinedExpression(
                                                    django.db.models.expressions.CombinedExpression(
                                                        django.db.models.expressions.CombinedExpression(
                                                            django.db.models.expressions.CombinedExpression(
                                                                django.db.models.expressions.CombinedExpression(
                                                                    django.db.models.expressions.CombinedExpression(
                                                                        django.db.models.expressions.CombinedExpression(
                                                                            django.db.models.expressions.CombinedExpression(
                                                                                django.db.models.expressions.CombinedExpression(
                                                                                    django.db.models.expressions.CombinedExpression(
                                                                                        django.db.models.expressions.CombinedExpression(
                                                                                            django.db.models.expressions.CombinedExpression(
                                                                                                models.Case(
                                                                                                    models.When(
                                                                                                        milestone__isnull=False,
                                                                                                        then=1,
                                                                                                    ),
                                                                                                    default=0,
                                                                                                    output_field=models.IntegerField(),
                                                                                                ),
                                                                                                "+",
                                                                                                models.Case(
                                                                                                    models.When(
                                                                                                        status__isnull=False,
                                                                                                        then=1,
                                                                                                    ),
                                                                                                    default=0,
                                                                                                    output_field=models.IntegerField(),
                                                                                                ),
                                                                                            ),
                                                                                            "+",
                                                                                            models.Case(
                                                                                                models.When(
                                                                                                    priority__isnull=False,
                                                                                                    then=1,
                                                                                                ),
                                                                                                default=0,
                                                                                                output_field=models.IntegerField(),
                                                                                            ),
                                                                                        ),
                                                                                        "+",
                                                                                        models.Case(
                                                                                            models.When(
                                                                                                severity__isnull=False,
                                                                                                then=1,
                                                                                            ),
                                                                                            default=0,
                                                                                            output_field=models.IntegerField(),
                                                                                        ),
                                                                                    ),
                                                                                    "+",
                                                                                    models.Case(
                                                                                        models.When(
                                                                                            relativesize__isnull=False,
                                                                                            then=1,
                                                                                        ),
                                                                                        default=0,
                                                                                        output_field=models.IntegerField(),
                                                                                    ),
                                                                                ),
                                                                                "+",
                                                                                models.Case(
                                                                                    models.When(
                                                                                        planningstate__isnull=False,
                                                                                        then=1,
                                                                                    ),
                                                                                    default=0,
                                                                                    output_field=models.IntegerField(),
                                                                                ),
                                                                            ),
                                                                            "+",
                                                                            models.Case(
                                                                                models.When(
                                                                                    then=1,
                                                                                    upstream__isnull=False,
                                                                                ),
                                                                                default=0,
                                                                                output_field=models.IntegerField(),
                                                                            ),
                                                                        ),
                                                                        "+",
                                                                        models.Case(
                                                                            models.When(
                                                                                paritylevel__isnull=False,
                                                                                then=1,
                                                                            ),
                                                                            default=0,
                                                                            output_field=models.IntegerField(),
                                                                        ),
                                                                    ),
                                                                    "+",
                                                                    models.Case(
                                                                        models.When(
                                                                            section__isnull=False,
                                                                            then=1,
                                                                        ),
                                                                        default=0,
                                                                        output_field=models.IntegerField(),
                                                                    ),
                                                                ),
                                                                "+",
                                                                models.Case(
                                                                    models.When(
                                                                        cardreferencekind__isnull=False,
                                                                        then=1,
                                                                    ),
                                                                    default=0,
                                                                    output_field=models.IntegerField(),
                                                                ),
                                                            ),
                                                            "+",
                                                            models.Case(
                                                                models.When(
                                                                    cardreferencesource__isnull=False,
                                                                    then=1,
                                                                ),
                                                                default=0,
                                                                output_field=models.IntegerField(),
                                                            ),
                                                        ),
                                                        "+",
                                                        models.Case(
                                                            models.When(
                                                                boarddockind__isnull=False,
                                                                then=1,
                                                            ),
                                                            default=0,
                                                            output_field=models.IntegerField(),
                                                        ),
                                                    ),
                                                    "+",
                                                    models.Case(
                                                        models.When(
                                                            targetversion__isnull=False,
                                                            then=1,
                                                        ),
                                                        default=0,
                                                        output_field=models.IntegerField(),
                                                    ),
                                                ),
                                                "+",
                                                models.Case(
                                                    models.When(specdoc__isnull=False, then=1),
                                                    default=0,
                                                    output_field=models.IntegerField(),
                                                ),
                                            ),
                                            "+",
                                            models.Case(
                                                models.When(card__isnull=False, then=1),
                                                default=0,
                                                output_field=models.IntegerField(),
                                            ),
                                        ),
                                        "+",
                                        models.Case(
                                            models.When(cardreference__isnull=False, then=1),
                                            default=0,
                                            output_field=models.IntegerField(),
                                        ),
                                    ),
                                    "+",
                                    models.Case(
                                        models.When(parityclaim__isnull=False, then=1),
                                        default=0,
                                        output_field=models.IntegerField(),
                                    ),
                                ),
                                "+",
                                models.Case(
                                    models.When(carditem__isnull=False, then=1),
                                    default=0,
                                    output_field=models.IntegerField(),
                                ),
                            ),
                            "+",
                            models.Case(
                                models.When(label__isnull=False, then=1),
                                default=0,
                                output_field=models.IntegerField(),
                            ),
                        ),
                        "+",
                        models.Case(
                            models.When(boarddoc__isnull=False, then=1),
                            default=0,
                            output_field=models.IntegerField(),
                        ),
                    ),
                    models.Value(1),
                ),
                name="kanban_uuidmodel_exactly_one_link",
            ),
        ),
    ]
