# Generated by Django 6.0.5 on 2026-05-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0006_boarddoc_boarddockind_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="card",
            name="unique_card_id",
        ),
        migrations.RemoveIndex(
            model_name="card",
            name="kanban_card_number_aa2857_idx",
        ),
        migrations.AlterField(
            model_name="card",
            name="number",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
