# Generated by Django 6.0.5 on 2026-05-31 01:07

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0007_unique_card_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardDocCardReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("raw_text", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "board doc card reference",
                "verbose_name_plural": "board doc card references",
                "ordering": ["doc", "order"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="uuidmodel",
            name="kanban_uuidmodel_exactly_one_link",
        ),
        migrations.AddField(
            model_name="boarddoccardreference",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="board_doc_references",
                to="kanban.card",
            ),
        ),
        migrations.AddField(
            model_name="boarddoccardreference",
            name="doc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_references",
                to="kanban.boarddoc",
            ),
        ),
        migrations.AddField(
            model_name="uuidmodel",
            name="boarddoccardreference",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uuid",
                to="kanban.boarddoccardreference",
            ),
        ),
        migrations.AddConstraint(
            model_name="uuidmodel",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    django.db.models.expressions.CombinedExpression(
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        django.db.models.expressions.CombinedExpression(
                                            django.db.models.expressions.CombinedExpression(
                                                django.db.models.expressions.CombinedExpression(
                                                    django.db.models.expressions.CombinedExpression(
                                                        django.db.models.expressions.CombinedExpression(
                                                            django.db.models.expressions.CombinedExpression(
                                                                django.db.models.expressions.CombinedExpression(
                                                                    django.db.models.expressions.CombinedExpression(
                                                                        django.db.models.expressions.CombinedExpression(
                                                                            django.db.models.expressions.CombinedExpression(
                                                                                django.db.models.expressions.CombinedExpression(
                                                                                    django.db.models.expressions.CombinedExpression(
                                                                                        django.db.models.expressions.CombinedExpression(
                                                                                            django.db.models.expressions.CombinedExpression(
                                                                                                django.db.models.expressions.CombinedExpression(
                                                                                                    models.Case(
                                                                                                        models.When(
                                                                                                            milestone__isnull=False,
                                                                                                            then=1,
                                                                                                        ),
                                                                                                        default=0,
                                                                                                        output_field=models.IntegerField(),
                                                                                                    ),
                                                                                                    "+",
                                                                                                    models.Case(
                                                                                                        models.When(
                                                                                                            status__isnull=False,
                                                                                                            then=1,
                                                                                                        ),
                                                                                                        default=0,
                                                                                                        output_field=models.IntegerField(),
                                                                                                    ),
                                                                                                ),
                                                                                                "+",
                                                                                                models.Case(
                                                                                                    models.When(
                                                                                                        priority__isnull=False,
                                                                                                        then=1,
                                                                                                    ),
                                                                                                    default=0,
                                                                                                    output_field=models.IntegerField(),
                                                                                                ),
                                                                                            ),
                                                                                            "+",
                                                                                            models.Case(
                                                                                                models.When(
                                                                                                    severity__isnull=False,
                                                                                                    then=1,
                                                                                                ),
                                                                                                default=0,
                                                                                                output_field=models.IntegerField(),
                                                                                            ),
                                                                                        ),
                                                                                        "+",
                                                                                        models.Case(
                                                                                            models.When(
                                                                                                relativesize__isnull=False,
                                                                                                then=1,
                                                                                            ),
                                                                                            default=0,
                                                                                            output_field=models.IntegerField(),
                                                                                        ),
                                                                                    ),
                                                                                    "+",
                                                                                    models.Case(
                                                                                        models.When(
                                                                                            planningstate__isnull=False,
                                                                                            then=1,
                                                                                        ),
                                                                                        default=0,
                                                                                        output_field=models.IntegerField(),
                                                                                    ),
                                                                                ),
                                                                                "+",
                                                                                models.Case(
                                                                                    models.When(
                                                                                        then=1,
                                                                                        upstream__isnull=False,
                                                                                    ),
                                                                                    default=0,
                                                                                    output_field=models.IntegerField(),
                                                                                ),
                                                                            ),
                                                                            "+",
                                                                            models.Case(
                                                                                models.When(
                                                                                    paritylevel__isnull=False,
                                                                                    then=1,
                                                                                ),
                                                                                default=0,
                                                                                output_field=models.IntegerField(),
                                                                            ),
                                                                        ),
                                                                        "+",
                                                                        models.Case(
                                                                            models.When(
                                                                                section__isnull=False,
                                                                                then=1,
                                                                            ),
                                                                            default=0,
                                                                            output_field=models.IntegerField(),
                                                                        ),
                                                                    ),
                                                                    "+",
                                                                    models.Case(
                                                                        models.When(
                                                                            cardreferencekind__isnull=False,
                                                                            then=1,
                                                                        ),
                                                                        default=0,
                                                                        output_field=models.IntegerField(),
                                                                    ),
                                                                ),
                                                                "+",
                                                                models.Case(
                                                                    models.When(
                                                                        cardreferencesource__isnull=False,
                                                                        then=1,
                                                                    ),
                                                                    default=0,
                                                                    output_field=models.IntegerField(),
                                                                ),
                                                            ),
                                                            "+",
                                                            models.Case(
                                                                models.When(
                                                                    boarddockind__isnull=False,
                                                                    then=1,
                                                                ),
                                                                default=0,
                                                                output_field=models.IntegerField(),
                                                            ),
                                                        ),
                                                        "+",
                                                        models.Case(
                                                            models.When(
                                                                targetversion__isnull=False,
                                                                then=1,
                                                            ),
                                                            default=0,
                                                            output_field=models.IntegerField(),
                                                        ),
                                                    ),
                                                    "+",
                                                    models.Case(
                                                        models.When(specdoc__isnull=False, then=1),
                                                        default=0,
                                                        output_field=models.IntegerField(),
                                                    ),
                                                ),
                                                "+",
                                                models.Case(
                                                    models.When(card__isnull=False, then=1),
                                                    default=0,
                                                    output_field=models.IntegerField(),
                                                ),
                                            ),
                                            "+",
                                            models.Case(
                                                models.When(cardreference__isnull=False, then=1),
                                                default=0,
                                                output_field=models.IntegerField(),
                                            ),
                                        ),
                                        "+",
                                        models.Case(
                                            models.When(parityclaim__isnull=False, then=1),
                                            default=0,
                                            output_field=models.IntegerField(),
                                        ),
                                    ),
                                    "+",
                                    models.Case(
                                        models.When(carditem__isnull=False, then=1),
                                        default=0,
                                        output_field=models.IntegerField(),
                                    ),
                                ),
                                "+",
                                models.Case(
                                    models.When(label__isnull=False, then=1),
                                    default=0,
                                    output_field=models.IntegerField(),
                                ),
                            ),
                            "+",
                            models.Case(
                                models.When(boarddoc__isnull=False, then=1),
                                default=0,
                                output_field=models.IntegerField(),
                            ),
                        ),
                        "+",
                        models.Case(
                            models.When(boarddoccardreference__isnull=False, then=1),
                            default=0,
                            output_field=models.IntegerField(),
                        ),
                    ),
                    models.Value(1),
                ),
                name="kanban_uuidmodel_exactly_one_link",
            ),
        ),
        migrations.AddIndex(
            model_name="boarddoccardreference",
            index=models.Index(fields=["card"], name="kanban_boar_card_id_459870_idx"),
        ),
        migrations.AddConstraint(
            model_name="boarddoccardreference",
            constraint=models.UniqueConstraint(
                fields=("doc", "order"),
                name="unique_board_doc_card_reference_position",
            ),
        ),
    ]
