# Generated by Django 6.0.5 on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0008_board_doc_card_references"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="targetversion",
            constraint=models.CheckConstraint(
                condition=~models.Q(number=""),
                name="target_version_number_required",
            ),
        ),
    ]
