# Generated by Django 6.0.5 on 2026-05-31

import django.db.models.deletion
from django.db import migrations, models


def copy_target_version_milestones(apps, schema_editor):
    Card = apps.get_model("kanban", "Card")
    db_alias = schema_editor.connection.alias
    for card in (
        Card.objects.using(db_alias).filter(milestone__isnull=True).select_related("target_version")
    ):
        card.milestone_id = card.target_version.milestone_id
        card.save(update_fields=["milestone"])


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0009_target_version_number_required"),
    ]

    operations = [
        migrations.RunPython(
            copy_target_version_milestones,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="card",
            name="milestone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cards",
                to="kanban.milestone",
            ),
        ),
        migrations.AddConstraint(
            model_name="card",
            constraint=models.CheckConstraint(
                condition=models.Q(number__gte=1),
                name="card_number_required",
            ),
        ),
    ]
