# Generated by Django 6.0.5 on 2026-06-01

import django.db.models.deletion
from django.db import migrations, models


def move_spec_links_to_spec_docs(apps, schema_editor):
    Card = apps.get_model("kanban", "Card")
    SpecDoc = apps.get_model("kanban", "SpecDoc")
    db_alias = schema_editor.connection.alias

    for card in Card.objects.using(db_alias).filter(spec__isnull=False):
        SpecDoc.objects.using(db_alias).filter(pk=card.spec_id).update(card_id=card.pk)

    orphan_names = list(
        SpecDoc.objects.using(db_alias).filter(card__isnull=True).values_list("name", flat=True),
    )
    if orphan_names:
        raise ValueError(
            "Cannot require SpecDoc.card while orphan spec docs exist: " + ", ".join(orphan_names),
        )


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0010_card_number_and_milestone_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="specdoc",
            name="card",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spec_docs_during_migration",
                to="kanban.card",
            ),
        ),
        migrations.RunPython(
            move_spec_links_to_spec_docs,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="card",
            name="spec",
        ),
        migrations.AlterField(
            model_name="specdoc",
            name="card",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spec",
                to="kanban.card",
            ),
        ),
    ]
