# Generated by Django 6.0.5 on 2026-06-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0011_required_spec_doc_card"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boarddoc",
            options={
                "ordering": ["namespace", "order"],
                "verbose_name": "board doc",
                "verbose_name_plural": "board docs",
            },
        ),
        migrations.AddField(
            model_name="boarddoc",
            name="include_heading",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="boarddoc",
            name="namespace",
            field=models.SlugField(default="kanban"),
        ),
        migrations.AlterField(
            model_name="boarddoc",
            name="key",
            field=models.SlugField(),
        ),
        migrations.AddConstraint(
            model_name="boarddoc",
            constraint=models.UniqueConstraint(
                fields=("namespace", "key"),
                name="unique_board_doc_key_per_namespace",
            ),
        ),
    ]
