# Generated by Django 6.0.5 on 2026-06-02 03:13
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.lookups
from django.db import migrations, models

import apps.kanban.constraints


def _spec_path_from_url(url):
    marker = "docs/"
    if marker not in url:
        return ""
    return url[url.index(marker) :]


def _basename(path):
    return path.rsplit("/", 1)[-1]


def backfill_card_glossary_terms(apps, schema_editor):
    CardGlossaryTerm = apps.get_model("kanban", "CardGlossaryTerm")
    GlossarySpecMention = apps.get_model("glossary", "GlossarySpecMention")
    SpecDoc = apps.get_model("kanban", "SpecDoc")
    UUIDModel = apps.get_model("kanban", "UUIDModel")
    db_alias = schema_editor.connection.alias

    mentions_by_path = {}
    mentions_by_basename = {}
    mentions = GlossarySpecMention.objects.using(db_alias).order_by(
        "spec_path",
        "order",
        "term__title_sort",
    )
    for mention in mentions:
        row = (mention.term_id, mention.term_text, mention.order)
        mentions_by_path.setdefault(mention.spec_path, []).append(row)
        mentions_by_basename.setdefault(_basename(mention.spec_path), []).append(row)

    spec_docs = SpecDoc.objects.using(db_alias).order_by("card_id", "id")
    for spec_doc in spec_docs:
        spec_path = _spec_path_from_url(spec_doc.url)
        spec_mentions = mentions_by_path.get(spec_path) or mentions_by_basename.get(
            _basename(spec_path),
            [],
        )
        seen_terms = set()
        order = 0
        for term_id, term_text, _mention_order in spec_mentions:
            if term_id in seen_terms:
                continue
            seen_terms.add(term_id)
            link = CardGlossaryTerm.objects.using(db_alias).create(
                card_id=spec_doc.card_id,
                term_id=term_id,
                raw_text=term_text,
                order=order,
            )
            UUIDModel.objects.using(db_alias).create(cardglossaryterm_id=link.pk)
            order += 1


class Migration(migrations.Migration):
    dependencies = [
        ("glossary", "0002_remove_glossarydocument_glossary_document_key_required_and_more"),
        ("kanban", "0012_alter_boarddoc_options_boarddoc_include_heading_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardGlossaryTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("raw_text", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "card glossary term",
                "verbose_name_plural": "card glossary terms",
                "ordering": ["card", "order"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="uuidmodel",
            name="kanban_uuidmodel_exactly_one_link",
        ),
        migrations.AddField(
            model_name="cardglossaryterm",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="glossary_links",
                to="kanban.card",
            ),
        ),
        migrations.AddField(
            model_name="cardglossaryterm",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kanban_card_links",
                to="glossary.glossaryterm",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="glossary_terms",
            field=models.ManyToManyField(
                blank=True,
                related_name="kanban_cards",
                through="kanban.CardGlossaryTerm",
                to="glossary.glossaryterm",
            ),
        ),
        migrations.AddField(
            model_name="uuidmodel",
            name="cardglossaryterm",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uuid",
                to="kanban.cardglossaryterm",
            ),
        ),
        migrations.AddConstraint(
            model_name="uuidmodel",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    apps.kanban.constraints.OneHotLinkCount(
                        "milestone",
                        "status",
                        "priority",
                        "severity",
                        "relativesize",
                        "planningstate",
                        "upstream",
                        "paritylevel",
                        "section",
                        "cardreferencekind",
                        "cardreferencesource",
                        "boarddockind",
                        "targetversion",
                        "specdoc",
                        "card",
                        "cardreference",
                        "cardglossaryterm",
                        "parityclaim",
                        "carditem",
                        "label",
                        "boarddoc",
                        "boarddoccardreference",
                    ),
                    models.Value(1),
                ),
                name="kanban_uuidmodel_exactly_one_link",
            ),
        ),
        migrations.RunPython(backfill_card_glossary_terms, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="cardglossaryterm",
            index=models.Index(fields=["term"], name="kanban_card_term_id_d1f42c_idx"),
        ),
        migrations.AddIndex(
            model_name="cardglossaryterm",
            index=models.Index(fields=["card", "order"], name="kanban_card_card_id_e5f35b_idx"),
        ),
        migrations.AddConstraint(
            model_name="cardglossaryterm",
            constraint=models.UniqueConstraint(
                fields=("card", "term"),
                name="unique_glossary_term_per_card",
            ),
        ),
        migrations.AddConstraint(
            model_name="cardglossaryterm",
            constraint=models.UniqueConstraint(
                fields=("card", "order"),
                name="unique_card_glossary_term_position",
            ),
        ),
    ]
