# Generated by Django 6.0.5 on 2026-06-23 03:49

import django.db.models.deletion
import django.db.models.lookups
from django.db import migrations, models

import apps.kanban.constraints


def _spec_path_from_url(url):
    marker = "docs/"
    if marker not in url:
        return ""
    return url[url.index(marker) :]


def _basename(path):
    return path.rsplit("/", 1)[-1]


def backfill_card_glossary_terms(apps, schema_editor):
    CardGlossaryTerm = apps.get_model("kanban", "CardGlossaryTerm")
    GlossarySpecMention = apps.get_model("glossary", "GlossarySpecMention")
    SpecDoc = apps.get_model("kanban", "SpecDoc")
    UUIDModel = apps.get_model("kanban", "UUIDModel")
    db_alias = schema_editor.connection.alias

    mentions_by_path = {}
    mentions_by_basename = {}
    mentions = GlossarySpecMention.objects.using(db_alias).order_by(
        "spec_path",
        "order",
        "term__title_sort",
    )
    for mention in mentions:
        row = (mention.term_id, mention.term_text, mention.order)
        mentions_by_path.setdefault(mention.spec_path, []).append(row)
        mentions_by_basename.setdefault(_basename(mention.spec_path), []).append(row)

    spec_docs = SpecDoc.objects.using(db_alias).order_by("card_id", "id")
    for spec_doc in spec_docs:
        spec_path = _spec_path_from_url(spec_doc.url)
        spec_mentions = mentions_by_path.get(spec_path) or mentions_by_basename.get(
            _basename(spec_path),
            [],
        )
        seen_terms = set()
        order = 0
        for term_id, term_text, _mention_order in spec_mentions:
            if term_id in seen_terms:
                continue
            seen_terms.add(term_id)
            link = CardGlossaryTerm.objects.using(db_alias).create(
                card_id=spec_doc.card_id,
                term_id=term_id,
                raw_text=term_text,
                order=order,
            )
            UUIDModel.objects.using(db_alias).create(cardglossaryterm_id=link.pk)
            order += 1


def _delete_card_reference_source_uuid_rows(apps, schema_editor):
    """Drop UUID side-rows linked to CardReferenceSource before its field/model go.

    Their only link is ``cardreferencesource``, which is about to be removed;
    left in place they would become all-null rows that violate the recreated
    ``kanban_uuidmodel_exactly_one_link`` constraint.

    Pinned to ``schema_editor.connection.alias`` so the delete runs on the database
    being migrated, not the router default. Under the multi-DB (``FAKESHOP_SHARDED``)
    layout the ``shard_b`` test database is migrated after ``default`` has already run
    the later ``RemoveField`` dropping ``cardreferencesource``, so an unpinned query
    would hit ``default`` and raise ``no such column: ...cardreferencesource_id``.
    """
    uuid_model = apps.get_model("kanban", "UUIDModel")
    alias = schema_editor.connection.alias
    uuid_model.objects.using(alias).filter(cardreferencesource__isnull=False).delete()


class Migration(migrations.Migration):
    replaces = [
        ("kanban", "0013_card_glossary_terms"),
        ("kanban", "0014_relativesize_description"),
        ("kanban", "0015_alter_cardreference_options_and_more"),
        ("kanban", "0016_remove_card_relative_size_high"),
        ("kanban", "0017_packagefile_card_changed_files"),
        ("kanban", "0018_rename_packagefile_trackedpath"),
    ]

    dependencies = [
        ("glossary", "0002_remove_glossarydocument_glossary_document_key_required_and_more"),
        ("kanban", "0012_alter_boarddoc_options_boarddoc_include_heading_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardGlossaryTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("raw_text", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "card glossary term",
                "verbose_name_plural": "card glossary terms",
                "ordering": ["card", "order"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="uuidmodel",
            name="kanban_uuidmodel_exactly_one_link",
        ),
        migrations.AddField(
            model_name="cardglossaryterm",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="glossary_links",
                to="kanban.card",
            ),
        ),
        migrations.AddField(
            model_name="cardglossaryterm",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kanban_card_links",
                to="glossary.glossaryterm",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="glossary_terms",
            field=models.ManyToManyField(
                blank=True,
                related_name="kanban_cards",
                through="kanban.CardGlossaryTerm",
                to="glossary.glossaryterm",
            ),
        ),
        migrations.AddField(
            model_name="uuidmodel",
            name="cardglossaryterm",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uuid",
                to="kanban.cardglossaryterm",
            ),
        ),
        migrations.AddConstraint(
            model_name="uuidmodel",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    apps.kanban.constraints.OneHotLinkCount(
                        "milestone",
                        "status",
                        "priority",
                        "severity",
                        "relativesize",
                        "planningstate",
                        "upstream",
                        "paritylevel",
                        "section",
                        "cardreferencekind",
                        "cardreferencesource",
                        "boarddockind",
                        "targetversion",
                        "specdoc",
                        "card",
                        "cardreference",
                        "cardglossaryterm",
                        "parityclaim",
                        "carditem",
                        "label",
                        "boarddoc",
                        "boarddoccardreference",
                    ),
                    models.Value(1),
                ),
                name="kanban_uuidmodel_exactly_one_link",
            ),
        ),
        migrations.RunPython(
            code=backfill_card_glossary_terms,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name="cardglossaryterm",
            index=models.Index(fields=["term"], name="kanban_card_term_id_d1f42c_idx"),
        ),
        migrations.AddIndex(
            model_name="cardglossaryterm",
            index=models.Index(fields=["card", "order"], name="kanban_card_card_id_e5f35b_idx"),
        ),
        migrations.AddConstraint(
            model_name="cardglossaryterm",
            constraint=models.UniqueConstraint(
                fields=("card", "term"),
                name="unique_glossary_term_per_card",
            ),
        ),
        migrations.AddConstraint(
            model_name="cardglossaryterm",
            constraint=models.UniqueConstraint(
                fields=("card", "order"),
                name="unique_card_glossary_term_position",
            ),
        ),
        migrations.AddField(
            model_name="relativesize",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(
            code=_delete_card_reference_source_uuid_rows,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name="cardreference",
            options={
                "ordering": ["source_card", "order"],
                "verbose_name": "card reference",
                "verbose_name_plural": "card references",
            },
        ),
        migrations.RemoveConstraint(
            model_name="cardreference",
            name="unique_card_reference_position",
        ),
        migrations.RemoveConstraint(
            model_name="uuidmodel",
            name="kanban_uuidmodel_exactly_one_link",
        ),
        migrations.AddConstraint(
            model_name="uuidmodel",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    apps.kanban.constraints.OneHotLinkCount(
                        "milestone",
                        "status",
                        "priority",
                        "severity",
                        "relativesize",
                        "planningstate",
                        "upstream",
                        "paritylevel",
                        "section",
                        "cardreferencekind",
                        "boarddockind",
                        "targetversion",
                        "specdoc",
                        "card",
                        "cardreference",
                        "cardglossaryterm",
                        "parityclaim",
                        "carditem",
                        "label",
                        "boarddoc",
                        "boarddoccardreference",
                    ),
                    models.Value(1),
                ),
                name="kanban_uuidmodel_exactly_one_link",
            ),
        ),
        migrations.RemoveField(
            model_name="cardreference",
            name="source",
        ),
        migrations.RemoveField(
            model_name="uuidmodel",
            name="cardreferencesource",
        ),
        migrations.DeleteModel(
            name="CardReferenceSource",
        ),
        migrations.RemoveField(
            model_name="card",
            name="relative_size_high",
        ),
        migrations.CreateModel(
            name="PackageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("path", models.TextField(unique=True)),
                ("is_current", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "package file",
                "verbose_name_plural": "package files",
                "ordering": ["path"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="uuidmodel",
            name="kanban_uuidmodel_exactly_one_link",
        ),
        migrations.AddField(
            model_name="card",
            name="changed_files",
            field=models.ManyToManyField(
                blank=True,
                related_name="cards",
                to="kanban.packagefile",
            ),
        ),
        migrations.RenameModel(
            old_name="PackageFile",
            new_name="TrackedPath",
        ),
        migrations.AddField(
            model_name="uuidmodel",
            name="trackedpath",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uuid",
                to="kanban.trackedpath",
            ),
        ),
        migrations.AddField(
            model_name="trackedpath",
            name="is_directory",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelOptions(
            name="trackedpath",
            options={
                "ordering": ["path"],
                "verbose_name": "tracked path",
                "verbose_name_plural": "tracked paths",
            },
        ),
        migrations.AddConstraint(
            model_name="uuidmodel",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    apps.kanban.constraints.OneHotLinkCount(
                        "milestone",
                        "status",
                        "priority",
                        "severity",
                        "relativesize",
                        "planningstate",
                        "upstream",
                        "paritylevel",
                        "section",
                        "cardreferencekind",
                        "boarddockind",
                        "targetversion",
                        "specdoc",
                        "trackedpath",
                        "card",
                        "cardreference",
                        "cardglossaryterm",
                        "parityclaim",
                        "carditem",
                        "label",
                        "boarddoc",
                        "boarddoccardreference",
                    ),
                    models.Value(1),
                ),
                name="kanban_uuidmodel_exactly_one_link",
            ),
        ),
    ]
