# Generated by Django 6.0.5 on 2026-06-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0013_card_glossary_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="relativesize",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
