# Generated by Django 6.0.5 on 2026-06-06 21:05

import django.db.models.expressions
import django.db.models.lookups
from django.db import migrations, models


def _delete_card_reference_source_uuid_rows(apps, schema_editor):
    """Drop UUID side-rows linked to CardReferenceSource before its field/model go.

    Their only link is ``cardreferencesource``, which is about to be removed;
    left in place they would become all-null rows that violate the recreated
    ``kanban_uuidmodel_exactly_one_link`` constraint.

    Pinned to ``schema_editor.connection.alias`` so the delete runs on the database
    being migrated, not the router default. Under the multi-DB (``FAKESHOP_SHARDED``)
    layout the ``shard_b`` test database is migrated after ``default`` has already run
    the later ``RemoveField`` dropping ``cardreferencesource``, so an unpinned query
    would hit ``default`` and raise ``no such column: ...cardreferencesource_id``.
    """
    uuid_model = apps.get_model("kanban", "UUIDModel")
    alias = schema_editor.connection.alias
    uuid_model.objects.using(alias).filter(cardreferencesource__isnull=False).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0014_relativesize_description"),
    ]

    operations = [
        migrations.RunPython(
            _delete_card_reference_source_uuid_rows,
            migrations.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name="cardreference",
            options={
                "ordering": ["source_card", "order"],
                "verbose_name": "card reference",
                "verbose_name_plural": "card references",
            },
        ),
        migrations.RemoveConstraint(
            model_name="cardreference",
            name="unique_card_reference_position",
        ),
        migrations.RemoveConstraint(
            model_name="uuidmodel",
            name="kanban_uuidmodel_exactly_one_link",
        ),
        migrations.AddConstraint(
            model_name="uuidmodel",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    django.db.models.expressions.CombinedExpression(
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        django.db.models.expressions.CombinedExpression(
                                            django.db.models.expressions.CombinedExpression(
                                                django.db.models.expressions.CombinedExpression(
                                                    django.db.models.expressions.CombinedExpression(
                                                        django.db.models.expressions.CombinedExpression(
                                                            django.db.models.expressions.CombinedExpression(
                                                                django.db.models.expressions.CombinedExpression(
                                                                    django.db.models.expressions.CombinedExpression(
                                                                        django.db.models.expressions.CombinedExpression(
                                                                            django.db.models.expressions.CombinedExpression(
                                                                                django.db.models.expressions.CombinedExpression(
                                                                                    django.db.models.expressions.CombinedExpression(
                                                                                        django.db.models.expressions.CombinedExpression(
                                                                                            django.db.models.expressions.CombinedExpression(
                                                                                                django.db.models.expressions.CombinedExpression(
                                                                                                    models.Case(
                                                                                                        models.When(
                                                                                                            milestone__isnull=False,
                                                                                                            then=1,
                                                                                                        ),
                                                                                                        default=0,
                                                                                                        output_field=models.IntegerField(),
                                                                                                    ),
                                                                                                    "+",
                                                                                                    models.Case(
                                                                                                        models.When(
                                                                                                            status__isnull=False,
                                                                                                            then=1,
                                                                                                        ),
                                                                                                        default=0,
                                                                                                        output_field=models.IntegerField(),
                                                                                                    ),
                                                                                                ),
                                                                                                "+",
                                                                                                models.Case(
                                                                                                    models.When(
                                                                                                        priority__isnull=False,
                                                                                                        then=1,
                                                                                                    ),
                                                                                                    default=0,
                                                                                                    output_field=models.IntegerField(),
                                                                                                ),
                                                                                            ),
                                                                                            "+",
                                                                                            models.Case(
                                                                                                models.When(
                                                                                                    severity__isnull=False,
                                                                                                    then=1,
                                                                                                ),
                                                                                                default=0,
                                                                                                output_field=models.IntegerField(),
                                                                                            ),
                                                                                        ),
                                                                                        "+",
                                                                                        models.Case(
                                                                                            models.When(
                                                                                                relativesize__isnull=False,
                                                                                                then=1,
                                                                                            ),
                                                                                            default=0,
                                                                                            output_field=models.IntegerField(),
                                                                                        ),
                                                                                    ),
                                                                                    "+",
                                                                                    models.Case(
                                                                                        models.When(
                                                                                            planningstate__isnull=False,
                                                                                            then=1,
                                                                                        ),
                                                                                        default=0,
                                                                                        output_field=models.IntegerField(),
                                                                                    ),
                                                                                ),
                                                                                "+",
                                                                                models.Case(
                                                                                    models.When(
                                                                                        then=1,
                                                                                        upstream__isnull=False,
                                                                                    ),
                                                                                    default=0,
                                                                                    output_field=models.IntegerField(),
                                                                                ),
                                                                            ),
                                                                            "+",
                                                                            models.Case(
                                                                                models.When(
                                                                                    paritylevel__isnull=False,
                                                                                    then=1,
                                                                                ),
                                                                                default=0,
                                                                                output_field=models.IntegerField(),
                                                                            ),
                                                                        ),
                                                                        "+",
                                                                        models.Case(
                                                                            models.When(
                                                                                section__isnull=False,
                                                                                then=1,
                                                                            ),
                                                                            default=0,
                                                                            output_field=models.IntegerField(),
                                                                        ),
                                                                    ),
                                                                    "+",
                                                                    models.Case(
                                                                        models.When(
                                                                            cardreferencekind__isnull=False,
                                                                            then=1,
                                                                        ),
                                                                        default=0,
                                                                        output_field=models.IntegerField(),
                                                                    ),
                                                                ),
                                                                "+",
                                                                models.Case(
                                                                    models.When(
                                                                        boarddockind__isnull=False,
                                                                        then=1,
                                                                    ),
                                                                    default=0,
                                                                    output_field=models.IntegerField(),
                                                                ),
                                                            ),
                                                            "+",
                                                            models.Case(
                                                                models.When(
                                                                    targetversion__isnull=False,
                                                                    then=1,
                                                                ),
                                                                default=0,
                                                                output_field=models.IntegerField(),
                                                            ),
                                                        ),
                                                        "+",
                                                        models.Case(
                                                            models.When(
                                                                specdoc__isnull=False,
                                                                then=1,
                                                            ),
                                                            default=0,
                                                            output_field=models.IntegerField(),
                                                        ),
                                                    ),
                                                    "+",
                                                    models.Case(
                                                        models.When(card__isnull=False, then=1),
                                                        default=0,
                                                        output_field=models.IntegerField(),
                                                    ),
                                                ),
                                                "+",
                                                models.Case(
                                                    models.When(
                                                        cardreference__isnull=False,
                                                        then=1,
                                                    ),
                                                    default=0,
                                                    output_field=models.IntegerField(),
                                                ),
                                            ),
                                            "+",
                                            models.Case(
                                                models.When(
                                                    cardglossaryterm__isnull=False,
                                                    then=1,
                                                ),
                                                default=0,
                                                output_field=models.IntegerField(),
                                            ),
                                        ),
                                        "+",
                                        models.Case(
                                            models.When(parityclaim__isnull=False, then=1),
                                            default=0,
                                            output_field=models.IntegerField(),
                                        ),
                                    ),
                                    "+",
                                    models.Case(
                                        models.When(carditem__isnull=False, then=1),
                                        default=0,
                                        output_field=models.IntegerField(),
                                    ),
                                ),
                                "+",
                                models.Case(
                                    models.When(label__isnull=False, then=1),
                                    default=0,
                                    output_field=models.IntegerField(),
                                ),
                            ),
                            "+",
                            models.Case(
                                models.When(boarddoc__isnull=False, then=1),
                                default=0,
                                output_field=models.IntegerField(),
                            ),
                        ),
                        "+",
                        models.Case(
                            models.When(boarddoccardreference__isnull=False, then=1),
                            default=0,
                            output_field=models.IntegerField(),
                        ),
                    ),
                    models.Value(1),
                ),
                name="kanban_uuidmodel_exactly_one_link",
            ),
        ),
        migrations.RemoveField(
            model_name="cardreference",
            name="source",
        ),
        migrations.RemoveField(
            model_name="uuidmodel",
            name="cardreferencesource",
        ),
        migrations.DeleteModel(
            name="CardReferenceSource",
        ),
    ]
