# Generated by Django 6.0.5 on 2026-06-06 21:05
import django.db.models.expressions
import django.db.models.lookups
from django.db import migrations, models

import apps.kanban.constraints


def _delete_card_reference_source_uuid_rows(apps, schema_editor):
    """Drop UUID side-rows linked to CardReferenceSource before its field/model go.

    Their only link is ``cardreferencesource``, which is about to be removed;
    left in place they would become all-null rows that violate the recreated
    ``kanban_uuidmodel_exactly_one_link`` constraint.

    Pinned to ``schema_editor.connection.alias`` so the delete runs on the database
    being migrated, not the router default. Under the multi-DB (``FAKESHOP_SHARDED``)
    layout the ``shard_b`` test database is migrated after ``default`` has already run
    the later ``RemoveField`` dropping ``cardreferencesource``, so an unpinned query
    would hit ``default`` and raise ``no such column: ...cardreferencesource_id``.
    """
    uuid_model = apps.get_model("kanban", "UUIDModel")
    alias = schema_editor.connection.alias
    uuid_model.objects.using(alias).filter(cardreferencesource__isnull=False).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0014_relativesize_description"),
    ]

    operations = [
        migrations.RunPython(
            _delete_card_reference_source_uuid_rows,
            migrations.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name="cardreference",
            options={
                "ordering": ["source_card", "order"],
                "verbose_name": "card reference",
                "verbose_name_plural": "card references",
            },
        ),
        migrations.RemoveConstraint(
            model_name="cardreference",
            name="unique_card_reference_position",
        ),
        migrations.RemoveConstraint(
            model_name="uuidmodel",
            name="kanban_uuidmodel_exactly_one_link",
        ),
        migrations.AddConstraint(
            model_name="uuidmodel",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    apps.kanban.constraints.OneHotLinkCount(
                        "milestone",
                        "status",
                        "priority",
                        "severity",
                        "relativesize",
                        "planningstate",
                        "upstream",
                        "paritylevel",
                        "section",
                        "cardreferencekind",
                        "boarddockind",
                        "targetversion",
                        "specdoc",
                        "card",
                        "cardreference",
                        "cardglossaryterm",
                        "parityclaim",
                        "carditem",
                        "label",
                        "boarddoc",
                        "boarddoccardreference",
                    ),
                    models.Value(1),
                ),
                name="kanban_uuidmodel_exactly_one_link",
            ),
        ),
        migrations.RemoveField(
            model_name="cardreference",
            name="source",
        ),
        migrations.RemoveField(
            model_name="uuidmodel",
            name="cardreferencesource",
        ),
        migrations.DeleteModel(
            name="CardReferenceSource",
        ),
    ]
