# Generated by Django 6.0.5 on 2026-06-10 20:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0015_alter_cardreference_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="relative_size_high",
        ),
    ]
