# Generated by Django 6.0.5 on 2026-06-12 19:15
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.lookups
from django.db import migrations, models

import apps.kanban.constraints


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0016_remove_card_relative_size_high"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("path", models.TextField(unique=True)),
                ("is_current", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "package file",
                "verbose_name_plural": "package files",
                "ordering": ["path"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="uuidmodel",
            name="kanban_uuidmodel_exactly_one_link",
        ),
        migrations.AddField(
            model_name="card",
            name="changed_files",
            field=models.ManyToManyField(
                blank=True,
                related_name="cards",
                to="kanban.packagefile",
            ),
        ),
        migrations.AddField(
            model_name="uuidmodel",
            name="packagefile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uuid",
                to="kanban.packagefile",
            ),
        ),
        migrations.AddConstraint(
            model_name="uuidmodel",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    apps.kanban.constraints.OneHotLinkCount(
                        "milestone",
                        "status",
                        "priority",
                        "severity",
                        "relativesize",
                        "planningstate",
                        "upstream",
                        "paritylevel",
                        "section",
                        "cardreferencekind",
                        "boarddockind",
                        "targetversion",
                        "specdoc",
                        "packagefile",
                        "card",
                        "cardreference",
                        "cardglossaryterm",
                        "parityclaim",
                        "carditem",
                        "label",
                        "boarddoc",
                        "boarddoccardreference",
                    ),
                    models.Value(1),
                ),
                name="kanban_uuidmodel_exactly_one_link",
            ),
        ),
    ]
