# Generated by Django 6.0.5 on 2026-06-12 20:21
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.lookups
from django.db import migrations, models

import apps.kanban.constraints


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0017_packagefile_card_changed_files"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="uuidmodel",
            name="kanban_uuidmodel_exactly_one_link",
        ),
        migrations.RenameModel(
            old_name="PackageFile",
            new_name="TrackedPath",
        ),
        migrations.RenameField(
            model_name="uuidmodel",
            old_name="packagefile",
            new_name="trackedpath",
        ),
        migrations.AddField(
            model_name="trackedpath",
            name="is_directory",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelOptions(
            name="trackedpath",
            options={
                "ordering": ["path"],
                "verbose_name": "tracked path",
                "verbose_name_plural": "tracked paths",
            },
        ),
        migrations.AddConstraint(
            model_name="uuidmodel",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    apps.kanban.constraints.OneHotLinkCount(
                        "milestone",
                        "status",
                        "priority",
                        "severity",
                        "relativesize",
                        "planningstate",
                        "upstream",
                        "paritylevel",
                        "section",
                        "cardreferencekind",
                        "boarddockind",
                        "targetversion",
                        "specdoc",
                        "trackedpath",
                        "card",
                        "cardreference",
                        "cardglossaryterm",
                        "parityclaim",
                        "carditem",
                        "label",
                        "boarddoc",
                        "boarddoccardreference",
                    ),
                    models.Value(1),
                ),
                name="kanban_uuidmodel_exactly_one_link",
            ),
        ),
    ]
