# Generated by Django 6.0.5 on 2026-06-22 20:25

import django.db.models.lookups
from django.db import migrations, models

import apps.kanban.constraints


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0018_rename_packagefile_trackedpath"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="uuidmodel",
            name="kanban_uuidmodel_exactly_one_link",
        ),
        migrations.AddConstraint(
            model_name="uuidmodel",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    apps.kanban.constraints.OneHotLinkCount(
                        "milestone",
                        "status",
                        "priority",
                        "severity",
                        "relativesize",
                        "planningstate",
                        "upstream",
                        "paritylevel",
                        "section",
                        "cardreferencekind",
                        "boarddockind",
                        "targetversion",
                        "specdoc",
                        "trackedpath",
                        "card",
                        "cardreference",
                        "cardglossaryterm",
                        "parityclaim",
                        "carditem",
                        "label",
                        "boarddoc",
                        "boarddoccardreference",
                    ),
                    models.Value(1),
                ),
                name="kanban_uuidmodel_exactly_one_link",
            ),
        ),
    ]
