# Generated by Django 6.0.5 on 2026-06-02 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlossaryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("label", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "glossary category",
                "verbose_name_plural": "glossary categories",
                "ordering": ["order", "label"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GlossaryStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("label", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "glossary status",
                "verbose_name_plural": "glossary statuses",
                "ordering": ["order", "label"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GlossaryTermLinkKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("label", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "glossary term link kind",
                "verbose_name_plural": "glossary term link kinds",
                "ordering": ["order", "label"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GlossaryCategoryMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="glossary.glossarycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "glossary category membership",
                "verbose_name_plural": "glossary category memberships",
                "ordering": ["category", "order"],
            },
        ),
        migrations.CreateModel(
            name="GlossaryDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("title", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
                ("body", models.TextField(blank=True, default="")),
                ("include_heading", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "glossary document",
                "verbose_name_plural": "glossary documents",
                "ordering": ["order"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("key", ""), _negated=True),
                        name="glossary_document_key_required",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GlossaryTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("title", models.TextField(unique=True)),
                ("title_sort", models.TextField()),
                ("anchor", models.SlugField(max_length=200, unique=True)),
                ("status_text", models.TextField()),
                ("body", models.TextField(blank=True, default="")),
                ("entry_order", models.PositiveIntegerField(default=0)),
                ("index_order", models.PositiveIntegerField(default=0)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="terms",
                        through="glossary.GlossaryCategoryMembership",
                        to="glossary.glossarycategory",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="terms",
                        to="glossary.glossarystatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "glossary term",
                "verbose_name_plural": "glossary terms",
                "ordering": ["entry_order", "title_sort"],
            },
        ),
        migrations.AddField(
            model_name="glossarycategorymembership",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_memberships",
                to="glossary.glossaryterm",
            ),
        ),
        migrations.CreateModel(
            name="GlossaryAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("label", models.TextField()),
                ("normalized", models.TextField()),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="glossary.glossaryterm",
                    ),
                ),
            ],
            options={
                "verbose_name": "glossary alias",
                "verbose_name_plural": "glossary aliases",
                "ordering": ["term", "label"],
            },
        ),
        migrations.CreateModel(
            name="GlossaryTermLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("raw_label", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "source_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="glossary.glossaryterm",
                    ),
                ),
                (
                    "target_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="glossary.glossaryterm",
                    ),
                ),
                (
                    "kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="glossary.glossarytermlinkkind",
                    ),
                ),
            ],
            options={
                "verbose_name": "glossary term link",
                "verbose_name_plural": "glossary term links",
                "ordering": ["source_term", "kind", "order"],
            },
        ),
        migrations.AddField(
            model_name="glossaryterm",
            name="related_terms",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_from",
                through="glossary.GlossaryTermLink",
                to="glossary.glossaryterm",
            ),
        ),
        migrations.CreateModel(
            name="GlossarySpecMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("spec_path", models.TextField()),
                ("term_text", models.TextField()),
                ("notes", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spec_mentions",
                        to="glossary.glossaryterm",
                    ),
                ),
            ],
            options={
                "verbose_name": "glossary spec mention",
                "verbose_name_plural": "glossary spec mentions",
                "ordering": ["spec_path", "order"],
                "indexes": [
                    models.Index(fields=["spec_path"], name="glossary_gl_spec_pa_7fd0ca_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("spec_path", "term"), name="unique_glossary_term_per_spec",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("spec_path", ""), _negated=True),
                        name="glossary_spec_mention_path_required",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("term_text", ""), _negated=True),
                        name="glossary_spec_mention_text_required",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GlossarySourceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("label", models.TextField()),
                ("target", models.TextField()),
                ("kind", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="glossary.glossaryterm",
                    ),
                ),
            ],
            options={
                "verbose_name": "glossary source link",
                "verbose_name_plural": "glossary source links",
                "ordering": ["term", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("term", "order"), name="unique_glossary_source_link_position",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("label", ""), _negated=True),
                        name="glossary_source_link_label_required",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("target", ""), _negated=True),
                        name="glossary_source_link_target_required",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="glossarycategorymembership",
            constraint=models.UniqueConstraint(
                fields=("category", "term"), name="unique_glossary_term_per_category",
            ),
        ),
        migrations.AddConstraint(
            model_name="glossarycategorymembership",
            constraint=models.UniqueConstraint(
                fields=("category", "order"), name="unique_glossary_category_position",
            ),
        ),
        migrations.AddIndex(
            model_name="glossaryalias",
            index=models.Index(fields=["normalized"], name="glossary_gl_normali_d1e1e2_idx"),
        ),
        migrations.AddConstraint(
            model_name="glossaryalias",
            constraint=models.UniqueConstraint(
                fields=("term", "normalized"), name="unique_glossary_alias_per_term",
            ),
        ),
        migrations.AddConstraint(
            model_name="glossaryalias",
            constraint=models.CheckConstraint(
                condition=models.Q(("label", ""), _negated=True),
                name="glossary_alias_label_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="glossaryalias",
            constraint=models.CheckConstraint(
                condition=models.Q(("normalized", ""), _negated=True),
                name="glossary_alias_normalized_required",
            ),
        ),
        migrations.AddIndex(
            model_name="glossaryterm",
            index=models.Index(fields=["title_sort"], name="glossary_gl_title_s_05a3b4_idx"),
        ),
        migrations.AddIndex(
            model_name="glossaryterm",
            index=models.Index(
                fields=["status", "entry_order"], name="glossary_gl_status__438637_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="glossaryterm",
            constraint=models.CheckConstraint(
                condition=models.Q(("title", ""), _negated=True),
                name="glossary_term_title_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="glossaryterm",
            constraint=models.CheckConstraint(
                condition=models.Q(("title_sort", ""), _negated=True),
                name="glossary_term_title_sort_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="glossaryterm",
            constraint=models.CheckConstraint(
                condition=models.Q(("anchor", ""), _negated=True),
                name="glossary_term_anchor_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="glossaryterm",
            constraint=models.CheckConstraint(
                condition=models.Q(("status_text", ""), _negated=True),
                name="glossary_term_status_text_required",
            ),
        ),
        migrations.AddIndex(
            model_name="glossarytermlink",
            index=models.Index(
                fields=["target_term", "kind"], name="glossary_gl_target__dede3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="glossarytermlink",
            index=models.Index(
                fields=["source_term", "kind"], name="glossary_gl_source__c0831e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="glossarytermlink",
            constraint=models.UniqueConstraint(
                fields=("source_term", "kind", "order"), name="unique_glossary_term_link_position",
            ),
        ),
    ]
