# Generated by Django 6.0.5 on 2026-06-02 01:33

from django.db import migrations


def copy_glossary_documents_to_board_docs(apps, schema_editor):
    """Move glossary prose sections into the shared kanban.BoardDoc table."""
    database = schema_editor.connection.alias
    GlossaryDocument = apps.get_model("glossary", "GlossaryDocument")
    BoardDoc = apps.get_model("kanban", "BoardDoc")
    BoardDocKind = apps.get_model("kanban", "BoardDocKind")
    UUIDModel = apps.get_model("kanban", "UUIDModel")

    kind, _created = BoardDocKind.objects.using(database).get_or_create(
        key="glossary",
        defaults={
            "label": "Glossary",
            "order": 99,
        },
    )
    UUIDModel.objects.using(database).get_or_create(boarddockind=kind)
    for document in GlossaryDocument.objects.using(database).order_by("order"):
        board_doc, _created = BoardDoc.objects.using(database).update_or_create(
            namespace="glossary",
            key=document.key,
            defaults={
                "kind": kind,
                "title": document.title,
                "order": document.order,
                "body": document.body,
                "include_heading": document.include_heading,
            },
        )
        UUIDModel.objects.using(database).get_or_create(boarddoc=board_doc)


class Migration(migrations.Migration):
    dependencies = [
        ("glossary", "0001_initial"),
        ("kanban", "0012_alter_boarddoc_options_boarddoc_include_heading_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="glossarydocument",
            name="glossary_document_key_required",
        ),
        migrations.RunPython(
            copy_glossary_documents_to_board_docs,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name="GlossaryDocument",
        ),
    ]
